### ISSUE TITLE
FATAL ERROR: I can't get SDL to set any video mode: Passed a NULL data source

### ISSUE THREAD

**Issue by kekk** [egoboo/egoboo#88] opened 2015-03-09 22:21 UTC
Hi after successful compilation on ubuntu-gnome 14.10 I can't run it. I tried with nvidia and intel. No matter what I do I get the same error.
```
Starting Egoboo 2.9.0 ...
INFO: PhysFS file system version 2.0.3 has been initialized...
INFO: Initializing Linux file system...
INFO: Initializing SDL version 1.2.15... Success!
INFO: Intializing SDL Joystick... Success!
INFO: Initializing SDL_Image version 1.2.12... INFO: Intializing SDL Video... Success!
WARNING: Unable to load icon (icon.bmp)
INFO: Opening SDL Video Mode...
Failed!
FATAL ERROR: I can't get SDL to set any video mode: Passed a NULL data source
```

**Comment by penguinflyer5234** [comment] 2015-03-10 08:18
Try latest master (406da2204); though you need to install the data files as well.

**Comment by kekk** [comment] 2015-03-10 12:01
I got a little bit of progress
but I encountered another error.
Success!
INFO: Initializing SDL_image version 1.2.12... Success!
INFO: Initializing the SDL_ttf font handler version 2.0.11... Success!
FATAL ERROR: load_font() - Cannot load file! ("mp_data/font_new_shadow")

**Comment by penguinflyer5234** [comment] 2015-03-10 12:25
you need to install the data files with either:
`make install` if you used `make all`
`make PREFIX=<whatever> install` if you used `make PREFIX=<whatever> all`

**Comment by kekk** [comment] 2015-03-10 19:35
I did
kekk@kekk:~/source/egoboo-master$ sudo make install
make -C /home/kekk/source/egoboo-master/external/lua-5.2.3 linux
make[1]: Entering directory '/home/kekk/source/egoboo-master/external/lua-5.2.3'
cd src && make linux
make[2]: Entering directory '/home/kekk/source/egoboo-master/external/lua-5.2.3/src'
make all SYSCFLAGS="-DLUA_USE_LINUX" SYSLIBS="-Wl,-E -ldl -lreadline"
make[3]: Entering directory '/home/kekk/source/egoboo-master/external/lua-5.2.3/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/kekk/source/egoboo-master/external/lua-5.2.3/src'
make[2]: Leaving directory '/home/kekk/source/egoboo-master/external/lua-5.2.3/src'
make[1]: Leaving directory '/home/kekk/source/egoboo-master/external/lua-5.2.3'
make -C idlib
make[1]: Entering directory '/home/kekk/source/egoboo-master/idlib'
make[1]: 'libidlib.a' is up to date.
make[1]: Leaving directory '/home/kekk/source/egoboo-master/idlib'
make -C egolib
make[1]: Entering directory '/home/kekk/source/egoboo-master/egolib'
make[1]: 'libegolib.a' is up to date.
make[1]: Leaving directory '/home/kekk/source/egoboo-master/egolib'
make -C game
make[1]: Entering directory '/home/kekk/source/egoboo-master/game'
make[1]: 'egoboo-2.x' is up to date.
make[1]: Leaving directory '/home/kekk/source/egoboo-master/game'
######################################
# This command will install egoboo using the
# directory structure currently used in svn repository
#
mkdir -p /usr/local/games
install -m 755 game/egoboo-2.x /usr/local/games
make -C data install PROJ_NAME=egoboo-2.x
make[1]: Entering directory '/home/kekk/source/egoboo-master/data'
######################################
# Thank you for installing the data files for egoboo! 
#
# If you do not have root access on this machine, 
# you can specify a prefix on the command line: 
#     "make install PREFIX=$HOME/.local"
# where the environment variable PREFIX specifies a
# virtual root for your installation. In this example,
# it is a local installation for this username only.
#
mkdir -p /usr/local/share/games/egoboo-2.x
cp -rdf ./basicdat /usr/local/share/games/egoboo-2.x
cp -rdf ./modules /usr/local/share/games/egoboo-2.x
cp -rdf ./editor /usr/local/share/games/egoboo-2.x
mkdir -p /usr/local/etc/egoboo-2.x
cp -rdf ./setup.txt /usr/local/etc/egoboo-2.x/setup.txt
cp -rdf ./controls.txt /usr/local/etc/egoboo-2.x/controls.txt
#####################################
# Installation of the egoboo data files has completed
#####################################
make[1]: Leaving directory '/home/kekk/source/egoboo-master/data'
#####################################
# Egoboo installation is finished

and the same error:
INFO: Initializing the SDL_ttf font handler version 2.0.11... Success!
FATAL ERROR: load_font() - Cannot load file! ("mp_data/font_new_shadow")

**Comment by kekk** [comment] 2015-03-11 19:19
tried again and still the same error.

**Comment by penguinflyer5234** [comment] 2015-03-12 06:06
try `make clean` (or just delete `egolib/src/egolib/platform/file_linux.o`) and then `make all`

It would also help if you could tell us what egoboo outputs to stdout (run it in a terminal).

**Comment by kekk** [comment] 2015-03-12 09:58
I tried to google that but couldn't find any package that contains stdout.
stdout: command not found
sorry

**Comment by penguinflyer5234** [comment] 2015-03-12 10:08
stdout is just a abbreviation of standard output, if you run Egoboo inside a terminal (`gnome-terminal`), it should output something like this:
```
Initializing filesystem services...
Game directories are:
        Binaries: /usr/local/games/
        Data: /usr/local/share/games/egoboo-2.x/
        User Data: /home/neptunium/.egoboo-2.x
        Config Files: /usr/local/etc/egoboo-2.x/
```

**Comment by kekk** [comment] 2015-03-12 14:03
kekk@kekk:~$ egoboo-2.x 
Initializing filesystem services...
Game directories are:
	Binaries: /usr/local/games/
	Data: /usr/local/share/games/egoboo-2.x/
	User Data: /home/esor/.egoboo-2.x
	Config Files: /usr/local/etc/egoboo-2.x/

**Comment by penguinflyer5234** [comment] 2015-03-12 14:08
...
Can you verify if `/usr/local/share/games/egoboo-2.x/basicdat` has anything in it?
This is very strange...

**Comment by kekk** [comment] 2015-03-12 14:41
I downloaded a new egoboo-master and this time a new error

src/egolib/math/LERP.cpp:1:32: fatal error: egolib/Math/LERP.hpp: No such file or directory
 #include "egolib/Math/LERP.hpp"
                                ^
compilation terminated.
<builtin>: recipe for target 'src/egolib/math/LERP.o' failed
make[1]: *** [src/egolib/math/LERP.o] Error 1
make[1]: Leaving directory '/home/esor/egoboo-master/egolib'
Makefile:80: recipe for target 'egolib' failed
make: *** [egolib] Error 2

**Comment by kekk** [comment] 2015-03-12 14:49
I made the previous egoboo-master with prefix and this time worked!!!!
make PREFIX=/home/kekk/Documents/egoboo all

**Comment by penguinflyer5234** [comment] 2015-03-12 18:32
I can't reproduce this when `PREFIX` is `/usr/local`.

**Comment by kekk** [comment] 2015-03-12 19:02
It works from the prefix location and from the local couldn't get it to work. Maybe Ubuntu has something to do with it?

**Comment by michaelheilmann** [comment] 2015-04-27 09:52
I am closing this now as it remains undetermined if there was an issue.

**Closed by michaelheilmann** 2015-04-27 09:52 UTC
